### ISSUE TITLE
[BUG] Multiple Claim WRN

### ISSUE THREAD

**Issue by GAMBRUSH** [Steemhunt/neverlose.money-contract#10]
**Describe the bug**

Multiple Claim WRN

**To Reproduce**

if I click repeatedly on Claim Pending I get a lot of approve notifications on metamask

**Expected behavior**

A clear and concise description of what you expected to happen : 
Cost a lot of fees, you have to disable button after click it

**Screenshots**

![Screenshot from 2020-11-17 18-58-23](https://user-images.githubusercontent.com/47976675/99388797-b2224680-2908-11eb-8b5d-19fcd790e134.png)
![Screenshot from 2020-11-17 19-00-15](https://user-images.githubusercontent.com/47976675/99389008-f9a8d280-2908-11eb-81ad-717050f171b4.png)

**Bounty information**
1. Reporter's email address: gambrush@gmail.com
2. What crypto currency do you want to receive the bounty?: BTC
2. Wallet address to receive the bounty: 
1u65u6azRdBuQNBKvEUCmd8bnJp3vEZGR

**Comment by sydneyitguy** [comment]
Let's disable claim button while pending @ggomaeng
