### ISSUE TITLE
[BUG] Multiple Lock-up

### ISSUE THREAD

**Issue by GAMBRUSH** [Steemhunt/neverlose.money-contract#11]
**Describe the bug**

Multiple Lock-Up

**To Reproduce**

1. Fill Lock-up amount
2. repeadly click Lock-Up your (Coin Name)
3. Open Metamask notification

**Expected behavior**

Cost a lot of fees, you have to disable button after click it

**Screenshots**

![Screenshot from 2020-11-17 21-02-43](https://user-images.githubusercontent.com/47976675/99400488-996e5c80-2919-11eb-9451-31781ef23eb7.png)
![Screenshot from 2020-11-17 21-06-54](https://user-images.githubusercontent.com/47976675/99400527-a428f180-2919-11eb-9559-aa5355efe66d.png)

**Additional context**

gas fee will remain cut off

**Bounty information**
1. Reporter's email address: gambrush@gmail.com
2. What crypto currency do you want to receive the bounty?: BTC
2. Wallet address to receive the bounty: 1u65u6azRdBuQNBKvEUCmd8bnJp3vEZGR

**Comment by sydneyitguy** [comment]
Not a bug, but thanks for the report. We will handle the case @ggomaeng
