### ISSUE TITLE
[BUG] maximum 2 pending

### ISSUE THREAD

**Issue by skdi1006** [Steemhunt/neverlose.money-contract#12]
**Describe the bug**

i want 3 pending in sametime
but i can get maximum 2 pending

**Expected behavior**

i want get many pending in sametime

**Bounty information**
1. Reporter's email address: skdi1006@hanmail.net
2. What crypto currency do you want to receive the bounty?: eth
2. Wallet address to receive the bounty: 
0xeafd26ff7d1b28f36f305b6da52a2c0e647efbee

**Comment by sydneyitguy** [comment]
There's no limit on the number of maximum pending transaction.

Here's 3 pending transactions I tried:
![image](https://user-images.githubusercontent.com/1332279/99624255-4c9d9980-2a71-11eb-86a1-a474d981e8eb.png)

**Comment by skdi1006** [comment]
@sydneyitguy is it mobile? i cant 3 pending in sametime in monbile metamask browser.
