### ISSUE TITLE
[BUG] Wrong active lock-up value

### ISSUE THREAD

**Issue by skdi1006** [Steemhunt/neverlose.money-contract#13]
**Describe the bug**

0.0000001eth lockup 
display = 1 eth

**Screenshots**

![Screenshot_20201118-131957_MetaMask](https://user-images.githubusercontent.com/74197897/99483048-c6b21d80-29a0-11eb-81ad-07a2ffdc528f.jpg)
![Screenshot_20201118-131937_MetaMask](https://user-images.githubusercontent.com/74197897/99483058-cb76d180-29a0-11eb-8757-41097beb8759.jpg)

**Bounty information**
1. Reporter's email address: skdi1006@hanmail.net
2. What crypto currency do you want to receive the bounty?: eth
2. Wallet address to receive the bounty:
0xeafd26ff7d1b28f36f305b6da52a2c0e647efbee

**Comment by sydneyitguy** [comment]
Is this possible? @ggomaeng

**Comment by sydneyitguy** [comment]
The issue has fixed, and $10 (0.02112 ETH) bounty has been paid to the ETH address
TXHash: https://etherscan.io/tx/0x0ff849adfb93b45083b9504a7039dfcb22a4283a97ef29c0952a8bd8bf873363
