### ISSUE TITLE
My locked asset is less than the amount I locked from the beginning and I have a pending bonus from WETH that seems completely over the top

### ISSUE THREAD

**Issue by piero6758** [Steemhunt/neverlose.money-contract#18]
**Describe the bug**

I have accessed my account and I have noticed two clear errors that I would like you to correct to improve the platform for all users as it causes confusion.

I have blocked 0.02 WETH and in "Active blocked" it shows that I have 0.017666 WETH. Of course, in "Block feeding" the amount is correct.

The other clear mistake is that I have a pending bonus of 8.154045 WETH which seems completely over the top.

This platform has shown me in the short time that I have used it that it has a great future. I want to let you know that I do this without any interest, I am only communicating these errors for the good of the platform.

**To Reproduce**

I access the WETH panel of my account and at once I notice the two errors.

Expected behavior

I was expecting my WETH dashboard to show the correct amount blocked as well as the correct WETH bonus.

**Screenshots**

https://prntscr.com/wezq47

**Additional context**

**Bounty information**
1. Reporter's email address: geanpieroechenique@gmail.com
2. What crypto currency do you want to receive the bounty?: ETH
2. Wallet address to receive the bounty: 0x3e6dD89A26830c3929a2945Cc9B5e669D7793A69

**Comment by sydneyitguy** [comment]
Oh can you tell me the wallet address you used for the lock-up? so I can have a look at the raw data?
And what happens if you refresh the page? The error still exists?

**Comment by sydneyitguy** [comment]
And could you please do the following steps on Etherscan and submit the result here?

1. Go to https://etherscan.io/address/0x7edBE5aF30Ba6Ba2DE9EdDc72C2f585D1B0D5775#readProxyContract
2. Open up `10. earnedBonus` section
3. Put WETH token contract address on the input (0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2) like this
![image](https://user-images.githubusercontent.com/1332279/103474109-f51a7980-4de3-11eb-9c28-958840191d42.png)
4. Click `Query` button
5. Let me know the result like
![image](https://user-images.githubusercontent.com/1332279/103474133-272bdb80-4de4-11eb-9aaf-691bf8b65824.png)

**Comment by piero6758** [comment]
Wallet address I used for the blocked: 0x8c7793e02eB2E875559E36Eb44Fd99ac15188E51

Yes, the error exists after refreshing the page.

Results after following the steps on Etherscan: https://prntscr.com/wf9yhd

**Comment by ggomaeng** [comment]
Could you please hover your mouse over the value and post the screenshot including the tooltip, like below?

![image](https://user-images.githubusercontent.com/18402191/103487953-cee1e300-4dbd-11eb-939d-a9bb0583ef2f.png)

**Comment by sydneyitguy** [comment]
@piero6758 Oh you should put token address on Etherscan, NOT your wallet address.
Please try with this "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2" instead of your wallet address

**Comment by piero6758** [comment]
Today it shows me the voucher correctly: https://prntscr.com/wg3oz3

But two days ago I had the problem, he showed me a completely exaggerated voucher.

Etherscan result after entering correct address: https://prntscr.com/wg3os6

The error is not there today, but it was there for several days. In this screenshot I show it again: https://prntscr.com/wezq47

**Comment by sydneyitguy** [comment]
Ok then it seems it's probably a front-end bug we had like a week ago.
We fixed it before, but your client was loaded from your browser cache.

Thanks for your report and help figuring out the issue.

$10 (0.02112 ETH) bug bounty has been paid to the ETH address.
TX: https://etherscan.io/tx/0x2f01c90c2999a66b716c9e7f9f9df2ee24035fa32587600e9e83376ca4a64568
