### ISSUE TITLE
Various errors in my weth dashboard make my locked balance less

### ISSUE THREAD

**Issue by glame868** [Steemhunt/neverlose.money-contract#19]
**Describe the bug**

More than a week ago I have blocked 0.015 WETH and today it says I have 0.00225 WETH. My active investment is 13.08, this is another clear mistake. In addition, the return on investment is 0.01% and not 0.02% as it should be.

The errors still remain: I have an outstanding bonus of an extremely inflated sum of 4.250045 WETH.

**To Reproduce**

Today I logged into my account and noticed several errors in my weth dashboard, causing my locked balance of 0.015 WETH to go to 0.00225

**Expected behavior**

I was hoping that my locked asset was correct: 0.015 WETH, that my asset investment and ROI were correct. In addition, the pending WETH Bonus will be shown to me correctly and not this exaggerated sum.

**Screenshots**

1. https://prntscr.com/wipqya
2. https://prntscr.com/wipr1v
3. https://prntscr.com/wipr56

**Additional context**

**Bounty information**
1. Reporter's email address: mmorochitos@gmail.com
2. What crypto currency do you want to receive the bounty?: ETH 
2. Wallet address to receive the bounty: 0x392c03bCd7051b633640d492D00D7693fe04d585

**Comment by sydneyitguy** [comment]
I guess this bug is duplicated with https://github.com/Steemhunt/neverlose.money-contract/issues/18

Can you hard refresh (delete cache and refresh) and see if the issue is fixed?

**Comment by glame868** [comment]
Yesterday the problem persisted all day. Today the problem has disappeared, my balance is reflected correctly.

I really like this page and that is why I recommend it on my social networks. My intention is to report any error that comes my way to do good for both the page and the users.

Thank you!


Screenshot from yesterday: https://prnt.sc/wipr1v

Today's screenshot: https://prnt.sc/wjh2lx

**Comment by sydneyitguy** [comment]
It seems it was the same issue with the ticket #18 
Thank you for your report! 🙏🏻
