### ISSUE TITLE
[BUG] Multiple Approve

### ISSUE THREAD

**Issue by GAMBRUSH** [Steemhunt/neverlose.money-contract#2]
**Describe the bug**

Multiple Approve 

**To Reproduce**

if I click repeatedly on Approve My HUNT I get a lot of approve notifications on metamask

**Expected behavior**

A clear and concise description of what you expected to happen :
Cost a lot of fees

**Screenshots**

https://user-images.githubusercontent.com/47976675/98958806-41a8ad80-2535-11eb-8280-10ad3b632100.png
https://user-images.githubusercontent.com/47976675/98958819-453c3480-2535-11eb-9b25-2d3d7a85da5a.png

**Additional context**

**Bounty information**
1. Reporter's email address: gambrush@gmail.com
2. What crypto currency do you want to receive the bounty?: BTC
2. Wallet address to receive the bounty: 
1u65u6azRdBuQNBKvEUCmd8bnJp3vEZGR

**Comment by sydneyitguy** [comment]
The issue has fixed, and $10 (0.00062734 BTC) bounty has been paid to the BTC address
TXHash: https://bitpay.com/insight/#/BTC/mainnet/tx/85f1d590a1773fa0e9904133ae642727d8e8adfd703d3a8bffbb54196fcfb877
