### ISSUE TITLE
[BUG] Error on lock-up

### ISSUE THREAD

**Issue by donnert** [Steemhunt/neverlose.money-contract#3]
**Describe the bug**

Can't Lock-up

**To Reproduce**

 - Open Lock-up popup
 - Enter amount '0.123456789'
 - Click 'Lock-up your WBTC'

**Expected behavior**

Lock-up successfully.

**Screenshots**

![image](https://user-images.githubusercontent.com/6082620/99151815-05b24b80-26e1-11eb-82d3-ef9a43b8c9d7.png)

**Additional context**

**Bounty information**
1. Reporter's email address: donnertwave@gmail.com
2. What crypto currency do you want to receive the bounty?: ETH
2. Wallet address to receive the bounty: 0xcb3b84b72587E4D47276FEacA326Ad813348d5E4

**Comment by sydneyitguy** [comment]
Please have a look @ggomaeng

**Comment by sydneyitguy** [comment]
The issue has fixed, and $10 (0.02233 ETH) bounty has been paid to the ETH address
TXHash: https://etherscan.io/tx/0xc7b5b6d8cfebe540b08030d9f3dc35165a5289629f2d4e9424c6520010432e3c
