### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by donnert** [Steemhunt/neverlose.money-contract#4]
**Describe the bug**

Wrong calculation

**To Reproduce**

- Total WETH : 10
- Locked-up WETH :2, Remain : 8
- Lock-up WETH : 7.999999999
- Remain WETH : **0.000094864**
- Locked-up: 10.0 WETH

**Expected behavior**

Remain WETH : 0.000000001
Locked-up: 9.999999999

**Screenshots**

![image](https://user-images.githubusercontent.com/6082620/99152249-f8e32700-26e3-11eb-87ce-b7e55066b51f.png)
![image](https://user-images.githubusercontent.com/6082620/99152260-0698ac80-26e4-11eb-8dbc-6ca30f44656e.png)

**Additional context**

**Bounty information**
1. Reporter's email address: donnertwave@gmail.com
2. What crypto currency do you want to receive the bounty?: ETH
2. Wallet address to receive the bounty: 0xcb3b84b72587E4D47276FEacA326Ad813348d5E4

**Comment by sydneyitguy** [comment]
I guess this is probably because there was a pending bonus that is automatically claimed with a new lock-up.
Can you post the transaction hash URL so I can have a look?

**Comment by donnert** [comment]
https://goerli.etherscan.io/tx/0x69365f176406dbbeb6a60c610c572072c202a69d29c751d018983e925628989c

this is link for issue
check this

thank you

2020년 11월 15일 (일) 15:04, sydneyitguy <notifications@github.com>님이 작성:

**Comment by sydneyitguy** [comment]
On the transaction, you can see "0.000094863315691384 WETH" was claimed during the transaction.

Note that
![image](https://user-images.githubusercontent.com/1332279/99199087-fbc34200-27df-11eb-9c54-fcc2e8f82e01.png)

I will close this issue
