### ISSUE TITLE
[BUG] Different coins cannot be pending at the same time.

### ISSUE THREAD

**Issue by skdi1006** [Steemhunt/neverlose.money-contract#5]
when i click claim pending in weth, i can't  claim pending in wbtc and hunt during pending
If i press a button in one type coin, there is no response in the other type coin.
unlock has same problem
when i unlock weth, i cant unlock wbtc during pending
Ethereum and Bitcoin have different networks and should be able to be pending at the same time.
Screenshot doesn't seem to mean anything. Because I cannot express that there is no response even if I press the wbtc pending button during weth pending

skdi1006@hanmail.net
eth
0xeafd26ff7d1b28f36f305b6da52a2c0e647efbee

**Comment by sydneyitguy** [comment]
That seems a minor front-end issue with loading state
- [ ] Different token pool shouldn't have dependency with each other (e.g. User can broadcast weth lock-up and while a hunt lock-up is pending)
- [ ] Lock-up & Withdrawal should make both "claim" buttons disabled on the same pool (shouldn't affect on different pool)

**Comment by sydneyitguy** [comment]
The issue has fixed, and $10 (0.02233 ETH) bounty has been paid to the ETH address
TXHash: https://etherscan.io/tx/0x5dec2f70d053345068d126e09c38450caca39276b0aeaed5cc484928ff2952b3
