### ISSUE TITLE
[BUG] 0.000000? lockup

### ISSUE THREAD

**Issue by skdi1006** [Steemhunt/neverlose.money-contract#6]
**Describe the bug**

i lockuped 0.0000007777weth. and  lockup feed show me nan quantity

**Screenshots**

![Screenshot_20201116-080356_MetaMask](https://user-images.githubusercontent.com/74197897/99199511-0e8b4600-27e3-11eb-92e9-42a795f3051c.jpg)

**Additional context**

This is a minor error. I think it's better to make a minimum lockup.
**Bounty information**
1. Reporter's email address: skdi1006@hanmail.net
2. What crypto currency do you want to receive the bounty?: eth
2. Wallet address to receive the bounty:
0xeafd26ff7d1b28f36f305b6da52a2c0e647efbee

**Comment by sydneyitguy** [comment]
NaN issue again @ggomaeng

**Comment by sydneyitguy** [comment]
The issue has fixed, and $10 (0.02233 ETH) bounty has been paid to the ETH address
TXHash: https://etherscan.io/tx/0x8eab3035e92f4b8066118964f1add250be1d1c19147514dcaac6fd5bece80cd0
