### ISSUE TITLE
[BUG] Lockup indication is abnormal

### ISSUE THREAD

**Issue by skdi1006** [Steemhunt/neverlose.money-contract#7]
**Describe the bug**

lockup wbtc 0.0000001
my active lock up 1
lockup wbtc 0.0000002
my active lock up 2

**Expected behavior**

lockup wbtc 0.0000001
my active lock up 0.0000001
lockup wbtc 0.0000002
my active lock up 0.0000002

**Screenshots**

![Screenshot_20201116-084842_MetaMask](https://user-images.githubusercontent.com/74197897/99200664-07b40180-27ea-11eb-9b3f-8d1c03f3c12f.jpg)

![Screenshot_20201116-085320_MetaMask](https://user-images.githubusercontent.com/74197897/99200561-6a58cd80-27e9-11eb-9d5f-da61a2c152a2.jpg)
![Screenshot_20201116-085444_MetaMask](https://user-images.githubusercontent.com/74197897/99200564-72187200-27e9-11eb-83af-a8b2974603f3.jpg)

**Additional context**

invest overview is working normally
but Lockup indication is abnormal.
**Bounty information**
1. Reporter's email address: skdi1006@hanmail.net
2. What crypto currency do you want to receive the bounty?: eth
2. Wallet address to receive the bounty:
0xeafd26ff7d1b28f36f305b6da52a2c0e647efbee

**Comment by sydneyitguy** [comment]
@ggomaeng seems like another NaN issue?

**Comment by sydneyitguy** [comment]
Seems like the same NaN issue with https://github.com/Steemhunt/neverlose.money-contract/issues/6
