### ISSUE TITLE
[BUG] gas customizing

### ISSUE THREAD

**Issue by skdi1006** [Steemhunt/neverlose.money-contract#8]
**Describe the bug**

default gwei 20
if i change it 22, i cant save it

**Screenshots**
![Screenshot_20201116-130051_MetaMask](https://user-images.githubusercontent.com/74197897/99211590-fda2fa80-280b-11eb-966f-807453b9ad90.jpg)

**Additional context**

**Bounty information**
1. Reporter's email address:skdi1006@hanmail.net
2. What crypto currency do you want to receive the bounty?: eth
2. Wallet address to receive the bounty:
0xeafd26ff7d1b28f36f305b6da52a2c0e647efbee

**Comment by sydneyitguy** [comment]
Thanks for reporting, but the bug is probably on the Metamask mobile app.
Neverlose.money front-end doesn't have a control over the gas price input.
