### ISSUE TITLE
[BUG] Pending UI bug

### ISSUE THREAD

**Issue by donnert** [Steemhunt/neverlose.money-contract#9]
**Describe the bug**

Pending UI bug

**To Reproduce**

- Change tab to WBTC
- Open Lock-up popup
- Click MAX and 'Lock-up your WBTC'
- SIgn metamask
- Click somewhere for close popup and change tab to WETH (before finish pending)
- Open Lock-up popup for WETH (you can see WBTC lock-up amount)
- Change tab to WBTC (Initial Price is - (-%))

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/6082620/99325929-a019b700-28ba-11eb-9114-d391ee2e26de.png)
![image](https://user-images.githubusercontent.com/6082620/99325944-a871f200-28ba-11eb-9959-196204ac7d7c.png)

**Additional context**

**Bounty information**
1. Reporter's email address: donnertwave@gmail.com
2. What crypto currency do you want to receive the bounty?: ETH
2. Wallet address to receive the bounty: 0xcb3b84b72587E4D47276FEacA326Ad813348d5E4

**Comment by sydneyitguy** [comment]
@ggomaeng Probably related to the time zone issue?

**Comment by ggomaeng** [comment]
@sydneyitguy This has to do with Coingecko API. Last time we updated the code to using UTC timestamp, and the API still returned nothing. I don't know what the condition is to reproduce this error, but two problems stated in this issue are unrelated to each other.

I fixed the first issue and pushed it.

**Comment by sydneyitguy** [comment]
The issue has fixed, and $10 (0.02013 ETH) bounty has been paid to the ETH address
TXHash: https://etherscan.io/tx/0x1b473ca64d072439f4079c9a42916c15738db8a4e1e6d1a33571fab6723b167a
